language: csharp
sudo: false
mono: none
dotnet: 2.1.401
dist: xenial

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  only:
    - master
    - release
    - dev
    - /^.*-wip$/
    - /^(.*\/)?ci-.*$/

install:
  - dotnet restore

script:
  - dotnet build src/Sandwych.Reporting/Sandwych.Reporting.csproj -f netstandard1.6
  - dotnet test src/Sandwych.Reporting.Tests/Sandwych.Reporting.Tests.csproj
